### ISSUE TITLE
Sending alarm messages from not existing child devices while mapper is stopped does not create the child devices when mapper is started again

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1362] opened 2022-08-24 12:41 UTC
**Describe the bug**

Sending alarm messages from not existing child devices (more than 2) while mapper is stopped does not create the child devices when mapper is started

**To Reproduce**
Precondition:
1. thin-edge is installed on DUT
2. Device is connected to c8y
3. no child devices are existing

Steps to reproduce:
1. Stop tedge-mapper `sudo systemctl stop tedge-mapper-c8y.service` 
2. Send alarm message for 1st child device `sudo tedge mqtt pub 'tedge/alarms/critical/temperature_high/child_device_1' '{ "message": "Temperature is very high", "time": "2021-01-03T05:30:45+00:00" }' -q 2 -r`
3. Send alarm message for 2nd child device `sudo tedge mqtt pub 'tedge/alarms/critical/temperature_high/child_device_2' '{ "message": "Temperature is very high", "time": "2021-01-03T05:30:45+00:00" }' -q 2 -r`
4. Send alarm message for 3rd child device `sudo tedge mqtt pub 'tedge/alarms/critical/temperature_high/child_device_3' '{ "message": "Temperature is very high", "time": "2021-01-03T05:30:45+00:00" }' -q 2 -r`
5. Start tedge-mapper `sudo systemctl start tedge-mapper-c8y.service`
6. Check on c8y and observe that only last 2 child devices will appear
7. Delete the two created child devices on c8y
8. Stop tedge mapper `sudo systemctl stop tedge-mapper-c8y.service` 
9. Repeat steps 1 - 5
10. Check on c8y, only last child device will be created

**Expected behavior**
All devices for which alarm was sent should be created on c8y

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version] Build: 818
 - Hardware [incl. revision] Raspberry pi 4GB
 - System-Architecture [e.g. result of "uname -a"] arch64
 - thin-edge.io version [e.g. 0.1.0]0.7.3

**Additional context**

**Comment by PradeepKiruvale** [comment] 2022-08-26 02:40
I have tested it and it's working as expected. So, I @gligorisaev will verify and try to reproduce it on his side.

**Comment by rina23q** [comment] 2022-08-30 08:28
@gligorisaev couldn't reproduce it again. So, close the issue.

**Closed by rina23q** 2022-08-30 08:28 UTC
Labels: bug
