### ISSUE TITLE
Allow the MQTT bridge keep alive interval to be configured

### ISSUE THREAD

**Issue by jarhodes314** [thin-edge/thin-edge.io#3068] opened 2024-08-19 09:14 UTC
**Is your feature improvement request related to a problem? Please describe.**
A customer is trying to minimise the data used by thin-edge. In doing this, they want to reduce the frequency of the MQTT keep-alive messages sent by mosquitto (and the built-in bridge) to the cloud. 

**Describe the solution you'd like**
We should add a configuration e.g. `mqtt.bridge.keepalive_interval` that affects the mosquitto bridge configuration and the built-in bridge. To configure it in mosquitto, we need to add the line:

```
keepalive_interval <no of seconds>
```

In the built-in bridge, we'll need to call [`set_keep_alive`](https://docs.rs/rumqttc/latest/rumqttc/struct.MqttOptions.html#method.set_keep_alive) on the cloud connection to configure this parameter.

Both default to 60 seconds, so that should be the configuration default.

**Comment by reubenmiller** [comment] 2024-08-27 22:40
Though we'll have to include a note to the users about what are some acceptable Cumulocity IoT keep alive values, because different IoT providers will have different recommended/acceptable values (I'm fairly certain that Cumulocity IoT will reject connections that have a keep alive in the range of 15 minutes etc.)

**Comment by reubenmiller** [comment] 2024-10-10 19:27
Duplicate of https://github.com/thin-edge/thin-edge.io/issues/3153

**Closed by reubenmiller** 2024-10-10 19:27 UTC
Labels: improvement, theme:mqtt
