### ISSUE TITLE
Observation: Message on tedge/errors is recently missing when we are not connected

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#958] opened 2022-03-01 13:22 UTC
**Describe the bug**

This is an observation about functionality that has recently changed and that was detected by two system-tests.
Not sure if the tests needs to be updated or else.

Usually, when we caused a parsing error e.g. with this: `sudo tedge mqtt pub tedge/measurements {` then we received a complaint on topic `tedge/errors` when tedge-mapper-c8y was running.

Recently, it looks like we really need to connect to C8y to get the same error message on the error topic.

**To Reproduce**

These two tests were testing the behavior:
```
pysys.py run tedge_mapper_c8y_positive
pysys.py run tedge_mapper_c8y_negative
```

**Expected behavior**

Test should pass or be fixed.
This could be achieved by subclassing the test to EnvironmentC8y. 

**Screenshots**

First approach. We connect before causing an error:

sudo tedge connect c8y
sudo tedge mqtt pub tedge/measurements {
![image](https://user-images.githubusercontent.com/75477722/156174446-64cdb8b6-21e6-4793-bfb8-1acaa9a2d204.png)

On MQTT:
![image](https://user-images.githubusercontent.com/75477722/156177586-47f9fd31-36f2-4c67-85b5-0fd12c2bb44d.png)

Second approach: we only start the tege-mapper-c8y service and then cause the error (no 

sudo systemctl start tedge-mapper-c8y.service
sudo tedge mqtt pub tedge/measurements {
![image](https://user-images.githubusercontent.com/75477722/156175075-b08bd0e4-8ee0-4410-8d4a-376afb177709.png)

On MQTT:
![image](https://user-images.githubusercontent.com/75477722/156177718-6ab54e1e-0695-40aa-8c12-f69244ef2097.png)

**Comment by rina23q** [comment] 2022-03-01 16:20
I think the tests need to be updated. 

- `tedge-mapper-c8y` tries to get its c8y object ID by using JWT token and HTTP request at the mapper start-up.
- If the device is not connected c8y, the retrieval fails.
- There is no use-case, which sending some Thin Edge JSON measurements to Cumulocity mapper without connecting to c8y (in other word, without having c8y mosquitto bridge confiugration).

**Comment by abelikt** [comment] 2022-03-02 08:57
Updating the tests is simple. We would just loose the opportunity to test the mapper in isolation (or we invent test-doubles for the JWT things : )

**Comment by abelikt** [comment] 2022-03-02 14:12
Oops I haven't seen the last message. Here is a draft PR that makes the test connect https://github.com/thin-edge/thin-edge.io/pull/967 . Lets decide how we continue with the message loop in advance.

**Comment by rina23q** [comment] 2022-03-08 11:29
We will fix to make the two loops (JWT token loop and translation loop) work independently.

**Comment by didier-wenzek** [comment] 2022-07-19 16:12
Before proposing a solution, here a description of the root causes of this issue.
* MQTT and HTTP aspects are tangled due to the protocol used by c8y.
* When there is no MQTT connection to c8y, the tedge mapper cannot send data to c8y via HTTP - because a JWT token must be requested via MQTT.
* Furthermore, to post an HTTP request to c8y one needs an internal id of the device - and this internal id has to be retrieved via HTTP.
* The c8y mapper try to get the internal id on start before doing anything else. So if there is no MQTT connection to c8y when the c8y mapper starts, it is stuck in this init loop. [Requesting the internal id only when required](https://github.com/thin-edge/thin-edge.io/pull/1094) just pushed the issue a bit further. If the device is not connect to c8y via MQTT when HTTP is required for the first time - say because an event needs to be sent over HTTP, then the mapper will be stuck in a loop trying to get a JWT token.
* Storing the internal id + JWT token once retrieved might help - but if there is no MQTT connection, then there is no way to have a fresh JWT token, hence HTTP connections will start failing too.
* The main difference between MQTT messages sent by the mapper and the HTTP requests posted by the mapper is *persistency*. The MQTT messages are persisted by the local MQTT broker, while the HTTP requests are lost when the mapper fails to post them - hence the infinity loop that is the root cause of this issue.

As a summary.
* If the c8y bridge is down, then there is no point posting an HTTP request to c8y.
* When the bridge is down, the c8y mapper must either fail or postpone and persist any request that requires HTTP.
* When the bridge is up again, the c8y mapper must send all the pending requests that require HTTP.

**Comment by reubenmiller** [comment] 2022-12-01 14:37
This ticket has expanded from the original description. The integration tests have switched to robot framework so I feel it is no longer applicable. Closing.

**Closed by reubenmiller** 2022-12-01 14:37 UTC
Labels: bug
