### ISSUE TITLE
0: File Error. Check permissions for /etc/tedge/mosquitto-conf/tedge-mosquitto.conf

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#495] opened 2021-10-13 07:03 UTC
I'm trying to run thin-edge.io on a custom board following the instuction of [,](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/004_connect.md) but get an error on connect comand.

```
$ tedge connect c8y
Checking if systemd is available.

Checking if configuration for requested bridge already exists.

Validating the bridge certificates.

Saving configuration for requested bridge.

Error: failed to create bridge to connect Cumulocity cloud.

Caused by:
    0: File Error. Check permissions for /etc/tedge/mosquitto-conf/tedge-mosquitto.conf.
    1: failed to persist temporary file: Invalid cross-device link (os error 18)
    2: Invalid cross-device link (os error 18)
```

I run tedge and mosquitto as root and also my directories ar owned by root:
```
$ ll /etc/tedge
drwxrwxrwx    5 root     root           440 Oct 13 06:55 .
drwxr-xr-x   16 root     root          3464 Oct 13 05:58 ..
drwxrwxrwx    3 root     root           232 Oct 13 05:44 contrib
drwxrwxrwx    2 root     root           320 Oct 13 05:59 device-certs
drwxrwxrwx    2 root     root           160 Oct 13 05:42 mosquitto-conf
-rw-rw-rw-    1 tedge    tedge          102 Oct 13 06:55 tedge.toml
```

Is my custom platform missing some features? Or is it really a permission error?

Best, 
Artur

**Comment by toewsar** [comment] 2021-10-15 05:24
Hi, 
that wasn't the problem. I fixed it for me, but I think there should be a general solution.

I tried almost erverything. I also changed the ownership of the directories to default:
```
$ chown -R tedge:tedge /etc/tedge
$ chown -R mosquitto:mosquitto /etc/tedge/device-certs
```

But at least I had do set the TMPDIR to the same filesystem than /etc/tedge. 
My `/tmp` is mounted as tmpfs but `/etc` is mounted as ubifs.
The following line was the final successful trial.
```
$ mkdir /etc/tedge/tmp
$ chwon tedge:tedge /etc/tedge/tmp
$ TMPDIR=/etc/tedge/tmp tedge connect c8y
```

The problem seems to be the rename() which is called in [persist_tempfile()](https://github.com/thin-edge/thin-edge.io/blob/1e927975005e4c8498f752bdda1437c27ce387d4/tedge/src/cli/connect/command.rs#L527).

**Comment by didier-wenzek** [comment] 2021-10-15 09:05
Indeed your root cause analysis is correct. The configuration files are created as temporary files then renamed. That cannot be done across file-systems.

=> One needs to create the temporary file along the target file in the same directory.

**Comment by didier-wenzek** [comment] 2021-10-15 10:34
I might have been confusing. `tedge connect` will be fixed asap.

**Comment by didier-wenzek** [comment] 2021-10-15 11:49
A fix has been merged. Can you, please, double check that the connect command is now working as expected on your device.

**Closed as completed** 2021-10-25 06:18 UTC
Labels: bug
