### ISSUE TITLE
mosquitto stops to persisting messages when rust bridge disconnects

### ISSUE THREAD

**Issue by sagIoTPower** [thin-edge/thin-edge.io#3083] opened 2024-08-26 08:54 UTC
Hi,
 
we have the behaviour that mosquitto stops to persist messages when the connection tedge_mqtt_bridge to the cloud is interrupted: (see screenshot tedge_mqtt_bridge_disconnect):
 
`2024-08-23T06:42:30.112741403Z ERROR tedge_mqtt_bridge::health: MQTT bridge failed to connect to cloud broker: Mqtt state: Last pingreg isn't acked`
 
The persistence-store continues to grow, as expected, until: `Time 6:48:35 AM 08/23/2024`.

See screenshots ![persistence_store_grow_start_github](https://github.com/user-attachments/assets/aac18804-bddb-4155-927e-ac2c52725686) and
![persistence_store_grow_end_github](https://github.com/user-attachments/assets/81eec3e5-0ddf-44c7-8039-7b8e76c5e49e)

But then is stops to grow. Which is strange.
 
We use the rust bridge and thin edge 1.2

This error does not happen, when we switch to the mosquitto bridge.
Is it a bug or do we have to configure something?
 
When the connection is finally restored the before persisted messages are successfully transmitted. But these are the old messages, messages received after persistence_store_grow_end discarded.

**Comment by sagIoTPower** [comment] 2024-08-26 10:48
Hi,

we set `max_queued_messages` and `max_queued_bytes` to 0 ( no limitation).

With the Mosquitto Bridge, persistence worked perfectly. After about a quarter of an hour and about 300 KB of persisted data, we stopped the test.

![Bild](https://github.com/user-attachments/assets/aeb6d061-96c6-4a98-923e-a7d7fdd2001e)
 
With the Rust Bridge, persistence stopped after approx. 5 minutes and approx. 215 KB of persisted data. At the same time, we received the following output in the MQTT Broker log
 
       `Client tedge-mapper-bridge-c8y has exceeded timeout, disconnecting.`
 
The persisted messages are not rolling, i.e. when reconnecting, only the data directly after the disconnect is sent and not the data shortly before the reconnect.

**Comment by didier-wenzek** [comment] 2024-08-30 09:00
There are two independent issues here:

- If the too many messages are queued by mosquitto for the builtin bridge during a network interruption,
  then messages are silently dropped by mosquitto and definitely lost.
  - An entry is added in the mosquitto log telling that `Outgoing messages are being dropped for client tedge-mapper-bridge-c8y`.
  - The mosquitto clients are not even warned and can do nothing. 
  - => The recommendation is to configure mosquitto with `max_queued_messages` and `max_queued_bytes` set to `0` (no limit).
  - I did two experiments (1-hour then 10-hours, both with 2 messages per second) and I can confirm that  [this fixes the main issue](https://github.com/thin-edge/thin-edge.io/issues/3083#issue-2486321301)
- The [second comment ](https://github.com/thin-edge/thin-edge.io/issues/3083#issuecomment-2309913209) is about something different.
  - The error [`Client tedge-mapper-bridge-c8y has exceeded timeout, disconnecting.`](https://github.com/eclipse/mosquitto/issues/2124#issuecomment-794452620)  is due to the builtin bridge failing to timely send a keep alive message.
  - => We have to address this. If the builtin bridge fails for some to respond on-time and is disconnected by mosquitto,
    it should be able to properly reconnect to the local broker *even* if disconnected a that time from the cloud.

**Comment by didier-wenzek** [comment] 2024-09-13 17:27
This issue was a combination of:

- A mosquitto misconfiguration: in order to avoid message lost during network disconnection, one has to configure mosquitto with `max_queued_messages` and `max_queued_bytes` to `0`. i.e. to set no maximum on the number of messages queued by mosquitto and waiting to be delivered.
- A thin-edge bug: under heavy load, notably when the network is back after a long disconnection, the builtin bridge was failing to make any progress and being finally disconnected by mosquitto (as failing to timely send heart beats). This issue has been fixed by  https://github.com/thin-edge/thin-edge.io/pull/3122

**Comment by sagIoTPower** [comment] 2024-09-18 08:54
We look into using the build-in bridge since we ran into the following issues with the mosquitto bridge:
1. https://github.com/eclipse/mosquitto/issues/1334
2. https://github.com/eclipse/mosquitto/issues/2795

**Comment by gligorisaev** [comment] 2024-09-20 06:47
Tested with Raspberry Pi and can confirm that the problem is not reproducable

**Closed** 2024-10-01 11:37 UTC
Labels: bug, theme:mqtt, theme:bridge
