### ISSUE TITLE
tedge-agent fails to download binary from Cumulocity IoT due to 401 error

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2174] opened 2023-08-20 10:23 UTC
**Describe the bug**

The thin-edge.io software management plugin fails to download a binary stored in Cumulocity IoT if the JWT has expired (and this error does not trigger a renewal of the token).

**To Reproduce**

1. Start thin-edge.io and its components (only mosquitto, tedge-agent and the tedge-mapper-c8y are required)
2. Wait until the Cumulocity IoT token requested on startup as expired. On Cumulocity eu-latest the expiration is set to 1 hour (though decode the JWT to check the expiration timestamp)
3. Create a software package and version in Cumulocity IoT and upload a binary which is hosted within Cumulocity IoT (don't use an external URL)
4. On the thin-edge.io device trigger a software update using the software package uploaded in the previous step
5. If no bug is observed, the operation should be set to SUCCESSFUL. With the bug the operation is set to FAILED, and the error "Could not make a successful request to the remote server" is shown in the software update logs, as well as a corresponding error ("HTTP status client error (401 Unauthorized) for url") in the tedge-agent logs.

**Expected behavior**

* the tedge-agent should renew the Cumulocity IoT token if required so that the binary hosted in Cumulocity IoT can be downloaded successfully

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: `Alpine Linux 3.18`
 - Hardware [incl. revision]: Docker container running on `aarch64`
 - System-Architecture [e.g. result of "uname -a"]: `Linux cb069e118bbc 5.15.68-0-virt #1-Alpine SMP Fri, 16 Sep 2022 06:29:31 +0000 aarch64 Linux`
 - thin-edge.io version [e.g. 0.1.0]: `0.12.1~99+g3e0fe253`

**Additional context**

The following shows the logs from the failed attempt (with the tokens redacted):

**file: tedge-mapper-c8y**

```log
2023-08-20T09:20:35.983272265Z  INFO MQTT: send Message { topic: Topic { name: "c8y/s/ds" }, payload: "528,rmi_apk_demo001,example,1.2.3::apk,https://t493319102.eu-latest.cumulocity.com/inventory/binaries/29251966,install", qos: AtLeastOnce, retain: false }    
2023-08-20T09:20:35.984529224Z  INFO CumulocityMapper: recv Some(MqttMessage(Message { topic: Topic { name: "c8y/s/ds" }, payload: "528,rmi_apk_demo001,example,1.2.3::apk,https://t493319102.eu-latest.cumulocity.com/inventory/binaries/29251966,install", qos: AtLeastOnce, retain: false }))    
2023-08-20T09:20:35.985296932Z  INFO C8yMapper => C8YHttpProxy: send GetJwtToken(GetJwtToken)    
2023-08-20T09:20:35.985428932Z  INFO C8Y-REST: recv Some((0, GetJwtToken(GetJwtToken)))    
2023-08-20T09:20:35.985546765Z  INFO C8Y-REST: send (0, Ok(EventId("<<redacted>>")))    
2023-08-20T09:20:35.985642099Z  INFO C8yMapper => C8YHttpProxy: recv Some(Ok(EventId("<<redacted>>")))    
2023-08-20T09:20:35.98606064Z  INFO C8yMapper => Mqtt: send Message { topic: Topic { name: "tedge/commands/req/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","updateList":[{"type":"apk","modules":[{"name":"example","version":"1.2.3","url":"https://t493319102.eu-latest.cumulocity.com/inventory/binaries/29251966","auth":{"bearer":"<<redacted>>"},"action":"install"}]}]}", qos: AtLeastOnce, retain: false }    
2023-08-20T09:20:35.986202432Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "tedge/commands/req/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","updateList":[{"type":"apk","modules":[{"name":"example","version":"1.2.3","url":"https://t493319102.eu-latest.cumulocity.com/inventory/binaries/29251966","auth":{"bearer":"<<redacted>>"},"action":"install"}]}]}", qos: AtLeastOnce, retain: false }))    
2023-08-20T09:20:36.301883391Z  INFO MQTT: send Message { topic: Topic { name: "tedge/commands/res/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","status":"executing"}", qos: AtLeastOnce, retain: false }    
2023-08-20T09:20:36.301928849Z  INFO CumulocityMapper: recv Some(MqttMessage(Message { topic: Topic { name: "tedge/commands/res/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","status":"executing"}", qos: AtLeastOnce, retain: false }))    
2023-08-20T09:20:36.302009974Z  INFO C8yMapper => Mqtt: send Message { topic: Topic { name: "c8y/s/us" }, payload: "501,c8y_SoftwareUpdate
", qos: AtLeastOnce, retain: false }    
2023-08-20T09:20:36.302024557Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "c8y/s/us" }, payload: "501,c8y_SoftwareUpdate
", qos: AtLeastOnce, retain: false }))    
2023-08-20T09:20:37.124621266Z  INFO MQTT: send Message { topic: Topic { name: "tedge/commands/res/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","status":"failed","reason":"1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log","currentSoftwareList":[{"type":"apk","modules":[{"name":"alpine-baselayout","version":"3.4.3-r1"},{"name":"alpine-baselayout-data","version":"3.4.3-r1"},{"name":"alpine-keys","version":"2.4-r1"},{"name":"apk-tools","version":"2.14.0-r2"},{"name":"busybox","version":"1.36.1-r2"},{"name":"busybox-binsh","version":"1.36.1-r2"},{"name":"c-ares","version":"1.19.1-r0"},{"name":"ca-certificates","version":"20230506-r0"},{"name":"ca-certificates-bundle","version":"20230506-r0"},{"name":"cjson","version":"1.7.15-r4"},{"name":"ifupdown-ng","version":"0.12.1-r2"},{"name":"libc-utils","version":"0.7.2-r5"},{"name":"libcap2","version":"2.69-r0"},{"name":"libcrypto3","version":"3.1.2-r0"},{"name":"libssl3","version":"3.1.2-r0"},{"name":"libwebsockets","version":"4.3.2-r2"},{"name":"mosquitto","version":"2.0.15-r3"},{"name":"mosquitto-libs","version":"2.0.15-r3"},{"name":"mosquitto-openrc","version":"2.0.15-r3"},{"name":"musl","version":"1.2.4-r1"},{"name":"musl-utils","version":"1.2.4-r1"},{"name":"openrc","version":"0.48-r0"},{"name":"scanelf","version":"1.3.7-r1"},{"name":"ssl_client","version":"1.36.1-r2"},{"name":"sudo","version":"1.9.13_p3-r2"},{"name":"tedge-apk","version":"plugin-0.0.0rc0"},{"name":"zlib","version":"1.2.13-r1"}]}],"failures":[{"type":"apk","modules":[]}]}", qos: AtLeastOnce, retain: false }    
2023-08-20T09:20:37.125599308Z  INFO CumulocityMapper: recv Some(MqttMessage(Message { topic: Topic { name: "tedge/commands/res/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","status":"failed","reason":"1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log","currentSoftwareList":[{"type":"apk","modules":[{"name":"alpine-baselayout","version":"3.4.3-r1"},{"name":"alpine-baselayout-data","version":"3.4.3-r1"},{"name":"alpine-keys","version":"2.4-r1"},{"name":"apk-tools","version":"2.14.0-r2"},{"name":"busybox","version":"1.36.1-r2"},{"name":"busybox-binsh","version":"1.36.1-r2"},{"name":"c-ares","version":"1.19.1-r0"},{"name":"ca-certificates","version":"20230506-r0"},{"name":"ca-certificates-bundle","version":"20230506-r0"},{"name":"cjson","version":"1.7.15-r4"},{"name":"ifupdown-ng","version":"0.12.1-r2"},{"name":"libc-utils","version":"0.7.2-r5"},{"name":"libcap2","version":"2.69-r0"},{"name":"libcrypto3","version":"3.1.2-r0"},{"name":"libssl3","version":"3.1.2-r0"},{"name":"libwebsockets","version":"4.3.2-r2"},{"name":"mosquitto","version":"2.0.15-r3"},{"name":"mosquitto-libs","version":"2.0.15-r3"},{"name":"mosquitto-openrc","version":"2.0.15-r3"},{"name":"musl","version":"1.2.4-r1"},{"name":"musl-utils","version":"1.2.4-r1"},{"name":"openrc","version":"0.48-r0"},{"name":"scanelf","version":"1.3.7-r1"},{"name":"ssl_client","version":"1.36.1-r2"},{"name":"sudo","version":"1.9.13_p3-r2"},{"name":"tedge-apk","version":"plugin-0.0.0rc0"},{"name":"zlib","version":"1.2.13-r1"}]}],"failures":[{"type":"apk","modules":[]}]}", qos: AtLeastOnce, retain: false }))    
2023-08-20T09:20:37.125708683Z ERROR c8y_mapper_ext::converter: Received a failed software response: {"id":"f-kb8vdNLyYb646AachvU","status":"failed","reason":"1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log","currentSoftwareList":[{"type":"apk","modules":[{"name":"alpine-baselayout","version":"3.4.3-r1"},{"name":"alpine-baselayout-data","version":"3.4.3-r1"},{"name":"alpine-keys","version":"2.4-r1"},{"name":"apk-tools","version":"2.14.0-r2"},{"name":"busybox","version":"1.36.1-r2"},{"name":"busybox-binsh","version":"1.36.1-r2"},{"name":"c-ares","version":"1.19.1-r0"},{"name":"ca-certificates","version":"20230506-r0"},{"name":"ca-certificates-bundle","version":"20230506-r0"},{"name":"cjson","version":"1.7.15-r4"},{"name":"ifupdown-ng","version":"0.12.1-r2"},{"name":"libc-utils","version":"0.7.2-r5"},{"name":"libcap2","version":"2.69-r0"},{"name":"libcrypto3","version":"3.1.2-r0"},{"name":"libssl3","version":"3.1.2-r0"},{"name":"libwebsockets","version":"4.3.2-r2"},{"name":"mosquitto","version":"2.0.15-r3"},{"name":"mosquitto-libs","version":"2.0.15-r3"},{"name":"mosquitto-openrc","version":"2.0.15-r3"},{"name":"musl","version":"1.2.4-r1"},{"name":"musl-utils","version":"1.2.4-r1"},{"name":"openrc","version":"0.48-r0"},{"name":"scanelf","version":"1.3.7-r1"},{"name":"ssl_client","version":"1.36.1-r2"},{"name":"sudo","version":"1.9.13_p3-r2"},{"name":"tedge-apk","version":"plugin-0.0.0rc0"},{"name":"zlib","version":"1.2.13-r1"}]}],"failures":[{"type":"apk","modules":[]}]}    
2023-08-20T09:20:37.125718641Z  INFO C8yMapper => Mqtt: send Message { topic: Topic { name: "c8y/s/us" }, payload: "502,c8y_SoftwareUpdate,"1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log"
", qos: AtLeastOnce, retain: false }    
2023-08-20T09:20:37.125724933Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "c8y/s/us" }, payload: "502,c8y_SoftwareUpdate,"1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log"
", qos: AtLeastOnce, retain: false }))
```

**file: tedge-agent**

```log
2023-08-20T09:20:36.295657682Z  INFO plugin_sm::plugin_manager: Plugin activated: /etc/tedge/sm-plugins/apk
2023-08-20T09:20:36.301354224Z  INFO SoftwareManager: send SoftwareUpdateResponse(SoftwareUpdateResponse { response: SoftwareRequestResponse { id: "f-kb8vdNLyYb646AachvU", status: Executing, reason: None, current_software_list: None, failures: [] } })    
2023-08-20T09:20:36.301450641Z  INFO Mqtt-Request-Converter: recv Some(SoftwareResponse(SoftwareUpdateResponse(SoftwareUpdateResponse { response: SoftwareRequestResponse { id: "f-kb8vdNLyYb646AachvU", status: Executing, reason: None, current_software_list: None, failures: [] } })))    
2023-08-20T09:20:36.301459016Z  INFO MqttPublisher: send Message { topic: Topic { name: "tedge/commands/res/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","status":"executing"}", qos: AtLeastOnce, retain: false }    
2023-08-20T09:20:36.301486016Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "tedge/commands/res/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","status":"executing"}", qos: AtLeastOnce, retain: false }))    
2023-08-20T09:20:36.941909808Z ERROR plugin_sm::plugin: Download error: DownloadError {
    reason: "Could not make a successful request to the remote server",
    url: "https://t493319102.eu-latest.cumulocity.com/inventory/binaries/29251966",
    source_err: "HTTP status client error (401 Unauthorized) for url (https://t493319102.eu-latest.cumulocity.com/inventory/binaries/29251966)",
}
2023-08-20T09:20:37.124109349Z  INFO SoftwareManager: send SoftwareUpdateResponse(SoftwareUpdateResponse { response: SoftwareRequestResponse { id: "f-kb8vdNLyYb646AachvU", status: Failed, reason: Some("1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log"), current_software_list: Some([SoftwareRequestResponseSoftwareList { plugin_type: "apk", modules: [SoftwareModuleItem { name: "alpine-baselayout", version: Some("3.4.3-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "alpine-baselayout-data", version: Some("3.4.3-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "alpine-keys", version: Some("2.4-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "apk-tools", version: Some("2.14.0-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "busybox", version: Some("1.36.1-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "busybox-binsh", version: Some("1.36.1-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "c-ares", version: Some("1.19.1-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "ca-certificates", version: Some("20230506-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "ca-certificates-bundle", version: Some("20230506-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "cjson", version: Some("1.7.15-r4"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "ifupdown-ng", version: Some("0.12.1-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libc-utils", version: Some("0.7.2-r5"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libcap2", version: Some("2.69-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libcrypto3", version: Some("3.1.2-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libssl3", version: Some("3.1.2-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libwebsockets", version: Some("4.3.2-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "mosquitto", version: Some("2.0.15-r3"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "mosquitto-libs", version: Some("2.0.15-r3"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "mosquitto-openrc", version: Some("2.0.15-r3"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "musl", version: Some("1.2.4-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "musl-utils", version: Some("1.2.4-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "openrc", version: Some("0.48-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "scanelf", version: Some("1.3.7-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "ssl_client", version: Some("1.36.1-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "sudo", version: Some("1.9.13_p3-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "tedge-apk", version: Some("plugin-0.0.0rc0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "zlib", version: Some("1.2.13-r1"), url: None, action: None, reason: None }] }]), failures: [SoftwareRequestResponseSoftwareList { plugin_type: "apk", modules: [] }] } })    
2023-08-20T09:20:37.124186308Z  INFO Mqtt-Request-Converter: recv Some(SoftwareResponse(SoftwareUpdateResponse(SoftwareUpdateResponse { response: SoftwareRequestResponse { id: "f-kb8vdNLyYb646AachvU", status: Failed, reason: Some("1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log"), current_software_list: Some([SoftwareRequestResponseSoftwareList { plugin_type: "apk", modules: [SoftwareModuleItem { name: "alpine-baselayout", version: Some("3.4.3-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "alpine-baselayout-data", version: Some("3.4.3-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "alpine-keys", version: Some("2.4-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "apk-tools", version: Some("2.14.0-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "busybox", version: Some("1.36.1-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "busybox-binsh", version: Some("1.36.1-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "c-ares", version: Some("1.19.1-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "ca-certificates", version: Some("20230506-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "ca-certificates-bundle", version: Some("20230506-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "cjson", version: Some("1.7.15-r4"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "ifupdown-ng", version: Some("0.12.1-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libc-utils", version: Some("0.7.2-r5"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libcap2", version: Some("2.69-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libcrypto3", version: Some("3.1.2-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libssl3", version: Some("3.1.2-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "libwebsockets", version: Some("4.3.2-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "mosquitto", version: Some("2.0.15-r3"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "mosquitto-libs", version: Some("2.0.15-r3"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "mosquitto-openrc", version: Some("2.0.15-r3"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "musl", version: Some("1.2.4-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "musl-utils", version: Some("1.2.4-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "openrc", version: Some("0.48-r0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "scanelf", version: Some("1.3.7-r1"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "ssl_client", version: Some("1.36.1-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "sudo", version: Some("1.9.13_p3-r2"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "tedge-apk", version: Some("plugin-0.0.0rc0"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "zlib", version: Some("1.2.13-r1"), url: None, action: None, reason: None }] }]), failures: [SoftwareRequestResponseSoftwareList { plugin_type: "apk", modules: [] }] } })))    
2023-08-20T09:20:37.124212933Z  INFO MqttPublisher: send Message { topic: Topic { name: "tedge/commands/res/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","status":"failed","reason":"1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log","currentSoftwareList":[{"type":"apk","modules":[{"name":"alpine-baselayout","version":"3.4.3-r1"},{"name":"alpine-baselayout-data","version":"3.4.3-r1"},{"name":"alpine-keys","version":"2.4-r1"},{"name":"apk-tools","version":"2.14.0-r2"},{"name":"busybox","version":"1.36.1-r2"},{"name":"busybox-binsh","version":"1.36.1-r2"},{"name":"c-ares","version":"1.19.1-r0"},{"name":"ca-certificates","version":"20230506-r0"},{"name":"ca-certificates-bundle","version":"20230506-r0"},{"name":"cjson","version":"1.7.15-r4"},{"name":"ifupdown-ng","version":"0.12.1-r2"},{"name":"libc-utils","version":"0.7.2-r5"},{"name":"libcap2","version":"2.69-r0"},{"name":"libcrypto3","version":"3.1.2-r0"},{"name":"libssl3","version":"3.1.2-r0"},{"name":"libwebsockets","version":"4.3.2-r2"},{"name":"mosquitto","version":"2.0.15-r3"},{"name":"mosquitto-libs","version":"2.0.15-r3"},{"name":"mosquitto-openrc","version":"2.0.15-r3"},{"name":"musl","version":"1.2.4-r1"},{"name":"musl-utils","version":"1.2.4-r1"},{"name":"openrc","version":"0.48-r0"},{"name":"scanelf","version":"1.3.7-r1"},{"name":"ssl_client","version":"1.36.1-r2"},{"name":"sudo","version":"1.9.13_p3-r2"},{"name":"tedge-apk","version":"plugin-0.0.0rc0"},{"name":"zlib","version":"1.2.13-r1"}]}],"failures":[{"type":"apk","modules":[]}]}", qos: AtLeastOnce, retain: false }    
2023-08-20T09:20:37.124226558Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "tedge/commands/res/software/update" }, payload: "{"id":"f-kb8vdNLyYb646AachvU","status":"failed","reason":"1 error, see device log file /var/log/tedge/agent/software-update-2023-08-20T09:20:36.301435432Z.log","currentSoftwareList":[{"type":"apk","modules":[{"name":"alpine-baselayout","version":"3.4.3-r1"},{"name":"alpine-baselayout-data","version":"3.4.3-r1"},{"name":"alpine-keys","version":"2.4-r1"},{"name":"apk-tools","version":"2.14.0-r2"},{"name":"busybox","version":"1.36.1-r2"},{"name":"busybox-binsh","version":"1.36.1-r2"},{"name":"c-ares","version":"1.19.1-r0"},{"name":"ca-certificates","version":"20230506-r0"},{"name":"ca-certificates-bundle","version":"20230506-r0"},{"name":"cjson","version":"1.7.15-r4"},{"name":"ifupdown-ng","version":"0.12.1-r2"},{"name":"libc-utils","version":"0.7.2-r5"},{"name":"libcap2","version":"2.69-r0"},{"name":"libcrypto3","version":"3.1.2-r0"},{"name":"libssl3","version":"3.1.2-r0"},{"name":"libwebsockets","version":"4.3.2-r2"},{"name":"mosquitto","version":"2.0.15-r3"},{"name":"mosquitto-libs","version":"2.0.15-r3"},{"name":"mosquitto-openrc","version":"2.0.15-r3"},{"name":"musl","version":"1.2.4-r1"},{"name":"musl-utils","version":"1.2.4-r1"},{"name":"openrc","version":"0.48-r0"},{"name":"scanelf","version":"1.3.7-r1"},{"name":"ssl_client","version":"1.36.1-r2"},{"name":"sudo","version":"1.9.13_p3-r2"},{"name":"tedge-apk","version":"plugin-0.0.0rc0"},{"name":"zlib","version":"1.2.13-r1"}]}],"failures":[{"type":"apk","modules":[]}]}", qos: AtLeastOnce, retain: false }))
```

**software-update logs**

```logs
----- $ Downloading: https://t493319102.eu-latest.cumulocity.com/inventory/binaries/29251966 to /tmp/example_1.2.3 
error: DownloadError error: "Could not make a successful request to the remote server" for "https://t493319102.eu-latest.cumulocity.com/inventory/binaries/29251966"
```

**Comment by didier-wenzek** [comment] 2023-08-21 07:35
Unfortunately, this is a design bug. The jwt token is given by the c8y mapper to the agent. If the token expires before being used, then the agent has no way to refresh it.

The solution proposed for the [`tedge-configuration-plugin`](https://thin-edge.github.io/thin-edge.io/next/references/c8y-configuration-management/) is to give to the c8y mapper the responsibility to download the files. The same approach can be used for software updates. The agent will only have to operate local files.

**Comment by didier-wenzek** [comment] 2023-08-21 10:25
The design bug has been made more serious by [this PR](https://github.com/thin-edge/thin-edge.io/pull/2065) that caches the JWT tokens. It's not more enough to retry a software update operation, when it fails with a 401.

This will be fixed by : https://github.com/thin-edge/thin-edge.io/issues/2175

**Comment by jarhodes314** [comment] 2023-08-22 13:30
The idea of a local proxy seems sensible to me, and seems like a nice HTTP counterpart to the mosquitto broker providing (locally) unauthenticated access to Cumulocity over MQTT.

Things I would bear in mind:

- Would customers potentially want this service to be authenticated in some way?
- If this were to expand beyond GET requests, where we can easily retry the request if it's rejected with a 401 (and therefore we probably don't need to worry about determining validity ourselves), how do we assess whether the JWT we last used is valid? Do we look at the expiration date of the JWT, do we look at how long ago we received the 
JWT, or do we just transparently retry requests when they fail? Retrying non-GET requests is trickier as we would need to store the body, which could (potentially) be quite large

From my not-particularly-in-depth mental model of thin-edge, the mapper seems like a sensible place for this. I agree there is source for confusion between this and file transfer service port.

One other thing to consider is that JWTs on Cumulocity can be revoked, so the mapper cannot act as a source of truth for whether our request will be authorized (which does rather defeat the point of JWTs in the first place). This appears to happen if I attempt to access the UI with a (device) JWT. After that, no more requests will work with that JWT and a new one will need to be requested. This probably wouldn't cause an issue in practice, but creating a Cumulocity proxy does make this quite easy to do, since all you have to do is visit the webpage in your browser (although we can potentially limit the proxy to known APIs/block requests immediately to APIs we know won't work).

**Comment by didier-wenzek** [comment] 2023-08-22 14:31
> Would customers potentially want this service to be authenticated in some way?

At some point, yes. The same certificates should be used as for local MQTT connections.

> How do we assess whether the JWT we last used is valid?

The current approach is to request a new token on 401 or 403 and to only return the error when this fresh token is also rejected.

> Retrying non-GET requests is trickier as we would need to store the body, which could (potentially) be quite large

Yes, this approach is more problematic for POST and PUT request. Trying first with a HEAD request can help to check the token.

> One other thing to consider is that JWTs on Cumulocity can be revoked, so the mapper cannot act as a source of truth for whether our request will be authorized (which does rather defeat the point of JWTs in the first place). This appears to happen if I attempt to access the UI with a (device) JWT. After that, no more requests will work with that JWT and a new one will need to be requested. This probably wouldn't cause an issue in practice, but creating a Cumulocity proxy does make this quite easy to do, since all you have to do is visit the webpage in your browser (although we can potentially limit the proxy to known APIs/block requests immediately to APIs we know won't work).

This is why it's simpler to request a new token after an authentication or authorization response.

**Comment by didier-wenzek** [comment] 2023-09-26 13:43
The main issue has been solved by https://github.com/thin-edge/thin-edge.io/pull/2261:

- Tedge-agent should no more fail to download a software binary from C8Y because of an expired token (401 error).
- A new feature has been introduced: c8y-auth-proxy: however this c8y-auth-proxy is not documented yet.

The following has still to be done:
- [ ] Document c8y-auth-proxy as this is a user facing feature. How to configure the proxy local HTTP port. How to send HTTP requests to c8y using this proxy.
- [ ] Use c8y-auth-proxy to download not only software packages but also configuration files and firmware.
- [ ] Use c8y-auth-proxy to upload logs, configuration files, software lists and events.
- [ ] Consider to deprecate JWT handling as done by the c8y-http-proxy.

**Comment by jarhodes314** [comment] 2023-10-11 08:17
@gligorisaev I've created a PR with some public documentation: https://github.com/thin-edge/thin-edge.io/pull/2330.

**Comment by gligorisaev** [comment] 2023-10-31 09:34
QA has thoroughly checked the bug and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.

**Closed** 2023-10-31 10:20 UTC
Labels: bug, theme:software, theme:c8y
