### ISSUE TITLE
Restart operation stuck in executing

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#2150] opened 2023-08-11 08:31 UTC
**Describe the bug**
We've installed thin-edge on a custom board with a custom package-manager. 
We also had to relocate the `tmp.path` to a non-volatile path:
```shell
$ tedge config list
...
tmp.path=/mnt/data/tedge/download
...
```

When I trigger a restart from c8y the device restarts, but the agent does not set the operation to successful.
I checked the log, but I could find anything pointing me to the error.

Log:
```shell
$ cat /var/log/tedge-agent.err
2023-08-11T08:13:24.09699871Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-agent.lock"
2023-08-11T08:13:24.097237419Z  INFO tedge_agent::agent: tedge-agent starting
2023-08-11T08:13:24.097401085Z  INFO sm-agent: tedge_agent::agent: Starting tedge agent
2023-08-11T08:13:24.104584794Z  INFO Runtime: Started
2023-08-11T08:13:24.10618296Z  INFO Runtime: Running Signal-Handler-0
2023-08-11T08:13:24.109716335Z  INFO Runtime: Running HttpFileTransferServer-1
2023-08-11T08:13:24.122435544Z  INFO Runtime: Running MQTT-2
2023-08-11T08:13:24.14085996Z  INFO Runtime: Running RestartManagerActor-3
2023-08-11T08:13:24.140973794Z  INFO Runtime: Running SoftwareManagerActor-4
2023-08-11T08:13:24.141049127Z  INFO Runtime: Running TedgeOperationConverter-5
2023-08-11T08:13:24.141117002Z  INFO Runtime: Running HealthMonitorActor-6
2023-08-11T08:13:24.141268585Z  INFO tedge-agent: send Message { topic: Topic { name: "tedge/health/tedge-agent" }, payload: "{"pid":2838,"status":"up","time":1691741604}", qos: AtLeastOnce, retain: true }
2023-08-11T08:13:24.621208585Z  INFO plugin_sm::plugin_manager: Plugin activated: /mnt/data/tedge/sm-plugins/cds
2023-08-11T08:13:33.55458817Z  INFO plugin_sm::plugin_manager: Plugin activated: /mnt/data/tedge/sm-plugins/ap
2023-08-11T08:13:33.554966295Z  INFO plugin_sm::plugin_manager: Default plugin type: ap
2023-08-11T08:13:33.570519378Z ERROR mqtt_channel::connection: MQTT connection error: Timeout
2023-08-11T08:13:33.614210211Z  INFO mqtt_channel::connection: MQTT connection established
2023-08-11T08:13:33.619202461Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "tedge/health/tedge-agent" }, payload: "{"pid":2838,"status":"up","time":1691741604}", qos: AtLeastOnce, retain: true }))
2023-08-11T08:13:33.714825795Z  INFO MQTT: send Message { topic: Topic { name: "tedge/commands/req/software/list" }, payload: "{"id":"ZpDTcMeq4_HqEQ3S5Xe4P"}", qos: AtLeastOnce, retain: false }
2023-08-11T08:13:33.71507942Z  INFO Mqtt-Request-Converter: recv Some(MqttMessage(Message { topic: Topic { name: "tedge/commands/req/software/list" }, payload: "{"id":"ZpDTcMeq4_HqEQ3S5Xe4P"}", qos: AtLeastOnce, retain: false }))
2023-08-11T08:13:33.715203628Z  INFO SoftwareSender: send SoftwareListRequest(SoftwareListRequest { id: "ZpDTcMeq4_HqEQ3S5Xe4P" })

2023-08-11T08:13:33.715303753Z  INFO SoftwareManager: recv Some(SoftwareListRequest(SoftwareListRequest { id: "ZpDTcMeq4_HqEQ3S5Xe4P" }))
2023-08-11T08:13:33.723645586Z  INFO SoftwareManager: send SoftwareListResponse(SoftwareListResponse { response: SoftwareRequestResponse { id: "ZpDTcMeq4_HqEQ3S5Xe4P", status: Executing, reason: None, current_software_list: None, failures: [] } })
2023-08-11T08:13:33.737589878Z  INFO Mqtt-Request-Converter: recv Some(SoftwareResponse(SoftwareListResponse(SoftwareListResponse { response: SoftwareRequestResponse { id: "ZpDTcMeq4_HqEQ3S5Xe4P", status: Executing, reason: None, current_software_list: None, failures: [] } })))
2023-08-11T08:13:33.737821003Z  INFO MqttPublisher: send Message { topic: Topic { name: "tedge/commands/res/software/list" }, payload: "{"id":"ZpDTcMeq4_HqEQ3S5Xe4P","status":"executing"}", qos: AtLeastOnce, retain: false }
2023-08-11T08:13:33.738023628Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "tedge/commands/res/software/list" }, payload: "{"id":"ZpDTcMeq4_HqEQ3S5Xe4P","status":"executing"}", qos: AtLeastOnce, retain: false }))
2023-08-11T08:13:44.478300131Z  INFO SoftwareManager: send SoftwareListResponse(SoftwareListResponse { response: SoftwareRequestResponse { id: "ZpDTcMeq4_HqEQ3S5Xe4P", status: Successful, reason: None, current_software_list: Some([SoftwareRequestResponseSoftwareList { plugin_type: "ap", modules: [SoftwareModuleItem { name: "thin-edge", version: Some("0.12.0_0.8.4"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "CODESYS", version: Some("3.5.16.30-38"), url: None, action: None, reason: None }] }, SoftwareRequestResponseSoftwareList { plugin_type: "cds", modules: [] }]), failures: [] } })
2023-08-11T08:13:44.484829667Z  INFO Mqtt-Request-Converter: recv Some(SoftwareResponse(SoftwareListResponse(SoftwareListResponse { response: SoftwareRequestResponse { id: "ZpDTcMeq4_HqEQ3S5Xe4P", status: Successful, reason: None, current_software_list: Some([SoftwareRequestResponseSoftwareList { plugin_type: "ap", modules: [SoftwareModuleItem { name: "thin-edge", version: Some("0.12.0_0.8.4"), url: None, action: None, reason: None }, SoftwareModuleItem { name: "CODESYS", version: Some("3.5.16.30-38"), url: None, action: None, reason: None }] }, SoftwareRequestResponseSoftwareList { plugin_type: "cds", modules: [] }]), failures: [] } })))
2023-08-11T08:13:44.485580115Z  INFO MqttPublisher: send Message { topic: Topic { name: "tedge/commands/res/software/list" }, payload: "{"id":"ZpDTcMeq4_HqEQ3S5Xe4P","status":"successful","currentSoftwareList":[{"type":"ap","modules":[{"name":"thin-edge","version":"0.12.0_0.8.4"},{"name":"CODESYS","version":"3.5.16.30-38"}]},{"type":"cds","modules":[]}]}", qos: AtLeastOnce, retain: false }

2023-08-11T08:13:44.485750933Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "tedge/commands/res/software/list" }, payload: "{"id":"ZpDTcMeq4_HqEQ3S5Xe4P","status":"successful","currentSoftwareList":[{"type":"ap","modules":[{"name":"thin-edge","version":"0.12.0_0.8.4"},{"name":"CODESYS","version":"3.5.16.30-38"}]},{"type":"cds","modules":[]}]}", qos: AtLeastOnce, retain: false }))
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by toewsar** [comment] 2023-08-11 09:57
Hi, 
I've used the [on_shutdown.sh](https://github.com/thin-edge/tedge-demo-container/blob/main/images/common/utils/on_shutdown.sh) script as reboot action and added a `sync` before the final `reboot -r now` and know the operation changes to "successful". 
Therefore I assume that the latest changes to `/etc/tedge/.agent/restart-current-operation` are not written to disc.

**Comment by toewsar** [comment] 2023-08-11 10:55
I get now sometimes (maybe every other time) a "restart failed" response, but I checked the log of the agent and could only see, that the agent reports "successful".

```shell
$ cat /var/log/tedge-agent.err
2023-08-11T10:49:46.290369242Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-agent.lock"
2023-08-11T10:49:46.291770919Z  INFO tedge_agent::agent: tedge-agent starting
2023-08-11T10:49:46.292975052Z  INFO sm-agent: tedge_agent::agent: Starting tedge agent
2023-08-11T10:49:46.304583842Z  INFO Runtime: Started
2023-08-11T10:49:46.308766247Z  INFO Runtime: Running Signal-Handler-0
2023-08-11T10:49:46.31036805Z  INFO Runtime: Running HttpFileTransferServer-1
2023-08-11T10:49:46.360520695Z  INFO Runtime: Running MQTT-2
2023-08-11T10:49:46.360976323Z  INFO Runtime: Running RestartManagerActor-3
2023-08-11T10:49:46.361081657Z  INFO Runtime: Running SoftwareManagerActor-4
2023-08-11T10:49:46.361147699Z  INFO Runtime: Running TedgeOperationConverter-5
2023-08-11T10:49:46.361222491Z  INFO Runtime: Running TedgetoTeConverter-6
2023-08-11T10:49:46.364335055Z  INFO Runtime: Running HealthMonitorActor-7
2023-08-11T10:49:46.365002726Z  INFO tedge-agent: send Message { topic: Topic { name: "tedge/health/tedge-agent" }, payload: "{"pid":3128,"status":"up","time":1691750986}", qos: AtLeastOnce, retain: true }
2023-08-11T10:49:46.984963759Z  INFO plugin_sm::plugin_manager: Plugin activated: /mnt/data/tedge/sm-plugins/cds
2023-08-11T10:50:00.213581631Z  INFO plugin_sm::plugin_manager: Plugin activated: /mnt/data/tedge/sm-plugins/ap
2023-08-11T10:50:00.214045521Z  INFO plugin_sm::plugin_manager: Default plugin type: ap
2023-08-11T10:50:00.243015949Z ERROR mqtt_channel::connection: MQTT connection error: Timeout
2023-08-11T10:50:00.266983051Z  INFO tedge_agent::restart_manager::actor: Device restart successful.
2023-08-11T10:50:00.267124139Z  INFO RestartManager: send RestartOperationResponse { id: "pMB1jOsD7mnzJqSZ1b1bw", status: Successful }
2023-08-11T10:50:00.267479483Z  INFO Mqtt-Request-Converter: recv Some(RestartOperationResponse(RestartOperationResponse { id: "pMB1jOsD7mnzJqSZ1b1bw", status: Successful }))
2023-08-11T10:50:00.267607946Z  INFO MqttPublisher: send Message { topic: Topic { name: "tedge/commands/res/control/restart" }, payload: "{"id":"pMB1jOsD7mnzJqSZ1b1bw","status":"successful"}", qos: AtLeastOnce, retain: false }
2023-08-11T10:50:00.341418811Z  INFO mqtt_channel::connection: MQTT connection established
2023-08-11T10:50:00.34510122Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "tedge/health/tedge-agent" }, payload: "{"pid":3128,"status":"up","time":1691750986}", qos: AtLeastOnce, retain: true }))

2023-08-11T10:50:00.345502567Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "tedge/commands/res/control/restart" }, payload: "{"id":"pMB1jOsD7mnzJqSZ1b1bw","status":"successful"}", qos: AtLeastOnce, retain: false }))
```

What could be gone wrong?

**Comment by toewsar** [comment] 2023-08-11 11:11
According to the Log the mapper seems also to send the successful message, but c8y shows "failed" 😲.

```shell
$ cat /var/log/tedge-mapper-c8y.err
...
2023-08-11T11:05:14.291180198Z  INFO MQTT: send Message { topic: Topic { name: "tedge/commands/res/control/restart" }, payload: "{"id":"snOEGykPCFTNfJFluVeIw","status":"successful"}", qos: AtLeastOnce, retain: false }
2023-08-11T11:05:14.29216276Z  INFO CumulocityMapper: recv Some(MqttMessage(Message { topic: Topic { name: "tedge/commands/res/control/restart" }, payload: "{"id":"snOEGykPCFTNfJFluVeIw","status":"successful"}", qos: AtLeastOnce, retain: false }))
2023-08-11T11:05:14.292383741Z  INFO C8yMapper => Mqtt: send Message { topic: Topic { name: "c8y/s/us" }, payload: "503,c8y_Restart,
", qos: AtLeastOnce, retain: false }
2023-08-11T11:05:14.292764406Z  INFO MQTT: recv Ok(Some(Message { topic: Topic { name: "c8y/s/us" }, payload: "503,c8y_Restart,
", qos: AtLeastOnce, retain: false }))
...
```

**Comment by reubenmiller** [comment] 2023-08-11 12:52
@toewsar Can you make sure all operations are cleared first before running the new test. It is best to clear all operations which are not already set to `SUCCESSFUL` or `FAILED` (just in case if there is a really old `PENDING` operation somewhere which is not visible in the UI.

**Comment by didier-wenzek** [comment] 2023-08-11 20:23
@toewsar Can you test [this PR](https://github.com/thin-edge/thin-edge.io/pull/2152) with your setting? 

This addresses the fact you noticed that the latest changes to /etc/tedge/.agent/restart-current-operation are not written to disc. Now the agent call fsync for all the files that required to resume the operation after the reboot.

About the other comments, I suspect that is might be caused by on old operation still PENDING (this confuses Cumulocity). However, this needs to be confirmed.

**Comment by didier-wenzek** [comment] 2023-08-16 13:30
This [PR](https://github.com/thin-edge/thin-edge.io/pull/2152) has been merged.

@toewsar Can you please test the latest version of thin-edge with your settings?

**Comment by toewsar** [comment] 2023-08-16 14:51
@didier-wenzek My test failed. The changes seem to be not efficient for my device. I cannot say why.
It seems that I need some sleep time between the operation and the actual reboot.

**Comment by reubenmiller** [comment] 2023-08-17 08:23
> @didier-wenzek My test failed. The changes seem to be not efficient for my device. I cannot say why. It seems that I need some sleep time between the operation and the actual reboot.

@toewsar  Just to eliminate any source of confusion, can you confirm which commit hash you re-built from?

**Comment by toewsar** [comment] 2023-08-17 08:41
```shell
$ git describe 
0.12.0-96-gf8aef0e7f4
```

**Comment by reubenmiller** [comment] 2023-08-17 09:22
It would be nice to understand a bit more about why the sync/flush is not enough to wait for the information to be written to the persistent partition...If there is a standard linux command that makes sense to convert this then we can add it, however I suspect the required command sounds very device specific (so using a custom shutdown command will be the way to go for you).

**Comment by toewsar** [comment] 2023-08-17 13:22
I'm not a RUST specialist and also not fimilar with async/await. 
Can you confirm that the write operation is finished when calling `sync`?

**Comment by toewsar** [comment] 2023-08-17 14:15
The `restart-current-operation` is cleared even if the mapper is not running on startup....

**Comment by didier-wenzek** [comment] 2023-08-18 07:11
> I'm not a RUST specialist and also not fimilar with async/await. Can you confirm that the write operation is finished when calling `sync`?

I confirm that a call to `file.sync_all().await?` returns only after the system call to `fsync` returns. The `await` just means that another thread can make progress meantime.

However, the behavior of [`fsync`](https://linux.die.net/man/3/fsync) is not guaranteed and depends on the file system.

**Comment by reubenmiller** [comment] 2023-08-18 16:54
@toewsar Would you be able to test the `sync; sync;` method in a custom shutdown script on your device?

For example, go through the following steps (I know you know this already, but I'm just adding it for the history):

1. Create a custom reboot command which just calls a script

    **file: /etc/tedge/system.toml**

    ```toml
    [system]
    reboot = ["/usr/bin/on_shutdown.sh"]
    ```

2. Create the script which will be called when tedge triggers a reboot;

    **file: /usr/bin/on_shutdown.sh**

    ```sh
    #!/bin/sh
    set -e
    sync; sync;
    ```

    Make sure the script is executable,

    ```sh
    chmod a+x /usr/bin/on_shutdown.sh
    ```

3. Ensure you have script and the underlying commands in your sudoers file (otherwise the reboot will fail):

    **file: /etc/sudoers.d/tedge**

    ```sh
    tedge ALL = (ALL) NOPASSWD: /usr/bin/tedge, /etc/tedge/sm-plugins/[a-zA-Z0-9]*, /bin/sync, /sbin/init, /sbin/shutdown, /usr/bin/on_shutdown.sh
    ```

4. Make sure you clear all of the existing PENDING and EXECUTING commands in Cumulocity

5. Trigger a restart operation via the UI

    The expected outcome is that the operation is successful, though I would also recommend repeating the test multiple times.

**Comment by reubenmiller** [comment] 2023-09-14 10:25
@toewsar are you happy to close this ticket then? We have already merged the improvement which explicitly calls `sync` before calling reboot, and from your last comment it seems to be more related to a hardware specific behaviour.

**Closed** 2023-09-14 10:28 UTC
Labels: bug
