### ISSUE TITLE
Health check commands

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2347] opened 2023-10-18 08:32 UTC
Update all thin-edge services and tedge-watchdog to use a new `te/+/+/+/+/cmd/health/check` topic for health check commands.

**Comment by didier-wenzek** [comment] 2023-10-18 08:50
Might be a duplicate of https://github.com/thin-edge/thin-edge.io/issues/2308

**Closed** 2023-10-18 09:21 UTC
