### ISSUE TITLE
`tedge-mapper-c8y` service restart is required after a change of supported operation file contents

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1705] opened 2023-02-01 12:04 UTC
**Describe the bug**
If you update a supported operation file in runtime of `tedge-mapper-c8y`, the mapper doesn't use the new content. The mapper needs to be restarted. For example,
1. Update the `command` field of an operation file to new path (from `/path/a` to `/path/b`).
2. `tedge-mapper-c8y` still looks up at `/path/a`.
3. After restart of `tedge-mapper-c8y`, it starts looking at `/path/b` finally.

**To Reproduce**
Prerequisites: 
* tedge and tedge-mapper are installed and already connected to c8y.
* `/etc/tedge/operations/c8y/c8y_Command` doesn't exist yet.

Steps:
1. Create a file `/etc/tedge/operations/command0.sh` then make it executable.
    ```shell
    echo -e '#!/bin/bash\necho "file: $0"\nexit 0' |  sudo tee /etc/tedge/operations/command0.sh
    sudo chmod +x /etc/tedge/operations/command0.sh
    ```
2. Create a file `/etc/tedge/operations/c8y/c8y_Command`.
    ```shell
    sudo -u tedge touch /etc/tedge/operations/c8y/c8y_Command
    ```
3. Add the following content to the file `/etc/tedge/operations/c8y/c8y_Command`.
    ```
    [exec]
    topic = "c8y/s/ds"
    on_message = "511"
    command = "/etc/tedge/operations/command0.sh"
    ```
4. Send a random text (e.g. "abc") with the "Shell" tab of c8y.
5. The operation stays pending. (It is because the mapper doesn't look up the updated content in `/etc/tedge/operations/c8y/c8y_Command`. Should have been marked "successful" without this bug)

**Workaround**

The current workaround to get the mapper to re-read the custom operation mapping files, you will need to restart the `tedge-mapper-c8y`  service, see below for an example:

```sh
sudo systemctl restart tedge-mapper-c8y.service
```
The pending operation should start processing the `tedge-mapper-c8y` service restarts. However if there are multiple operations of the same type (e.g. shell operations), then the status/result of the operation might be out of order (due to the id-less handling of operations in Cumulocity).

**Expected behavior**
The `tedge-mapper-c8y` should catch the contents update of supported operation files immediately. Restart should not be required.

**Screenshots**

**Environment (please complete the following information):**
 - OS [Ubuntu 20.04]
 - Hardware [incl. revision]
 - System-Architecture [amd64]
 - thin-edge.io version [0.9.0]

**Additional context**

**Comment by didier-wenzek** [comment] 2023-05-11 12:59
Once validated the fix for that issue, one has to close this PR https://github.com/thin-edge/thin-edge.io/pull/1927 documenting a workaround.

**Comment by gligorisaev** [comment] 2023-05-12 06:12
Before I validate the bug the one who raised it, in this case @rina23q should first confirm that the bug is fixed (and correct the text in "how to reproduce")

**Comment by reubenmiller** [comment] 2023-05-12 07:20
@rina23q After talking with @gligorisaev I made a few improvements to the formatting and description of some of the steps in the initial ticket description.

**Comment by gligorisaev** [comment] 2023-05-12 10:54
Bug still exists

**Comment by PradeepKiruvale** [comment] 2023-05-15 07:33
It works for me.

**Comment by reubenmiller** [comment] 2023-05-15 15:19
@gligorisaev It can be retested. The version is already available from cloudsmith.io, [0.10.0-264-gb245979f](https://cloudsmith.io/~thinedge/repos/tedge-main/packages/?q=version%3A0.10.0-264-gb245979f)

**Comment by gligorisaev** [comment] 2023-05-16 08:06
Tested and not reproducable,

**Closed** 2023-05-16 11:03 UTC
Labels: bug, theme:plugins
