### ISSUE TITLE
The mapper must not forward expired JWT tokens to the agent

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2175] opened 2023-08-21 10:23 UTC
The Cumulocity mapper [caches JWT tokens and refreshes them only on 401 authentication errors](https://github.com/thin-edge/thin-edge.io/pull/2065). This leads to an issue when these cached tokens are forwarded to the agent. The latter has currently no way to request a fresh token. The impacts are that all software update operations will fail till another operation triggers a token refresh.

The point here is to have a quick fix: [the jwt token forwarded by the mapper to the agent](https://github.com/thin-edge/thin-edge.io/blob/main/crates/extensions/c8y_mapper_ext/src/converter.rs#L467C16-L467C16) must be a fresh token.

The main design issue (i.e. the mapper sending a JWT token to the agent with no way for the later to request a fresh one) will be fix independently.

**Comment by PradeepKiruvale** [comment] 2023-08-30 06:35
The issue is addressed temporarily in this PR https://github.com/thin-edge/thin-edge.io/pull/2178. This is just a workaround. The real problem will be fixed in this ticket https://github.com/thin-edge/thin-edge.io/issues/2174

**Closed by PradeepKiruvale** 2023-08-30 06:35 UTC
Labels: bug
