### ISSUE TITLE
Installing tedge after uninstall is failing

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#2776] opened 2024-03-13 08:10 UTC
**Describe the bug**

Running test which is uninstalling previously installed tedge and than installing again is failing with unmet dependencies error

**To Reproduce**

1. Raspberry PI 3 with installed tedge (used the 192.168.193.16 and 192.168.193.144 from our environment)
2. Uninstalling tedge 
    ```
    curl -sSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/uninstall-thin-edge_io.sh | sudo sh -s purge
    ```
4. Installing tedge

    ```
    curl -fsSL https://thin-edge.io/install.sh | sh -s
    ```

Results in packages have unmet dependencies error:

```
pi@raspberrypi:~ $ curl -fsSL https://thin-edge.io/install.sh | sh -s
Thank you for trying thin-edge.io!

Package management dependencies met
Detected package manager: apt
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease                                                                              
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease                                                               
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease                                                                             
Hit:5 http://download.zerotier.com/debian/bullseye bullseye InRelease                                                                      
Get:6 https://dl.cloudsmith.io/public/thinedge/community/deb/debian bullseye InRelease [5187 B]                                            
Get:7 https://dl.cloudsmith.io/public/thinedge/tedge-main/deb/raspbian bullseye InRelease [4469 B]
Get:8 https://dl.cloudsmith.io/public/thinedge/tedge-release/deb/debian bullseye InRelease [4436 B]
Fetched 14.1 kB in 4s (3892 B/s)   
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.

Downloading https://dl.cloudsmith.io/public/thinedge/tedge-release/setup.deb.sh...OK
Using repository arch: aarch64
Executing the  setup script for the 'thinedge/tedge-release' repository ...

   OK: Checking for required executable 'curl' ... 
   OK: Checking for required executable 'apt-get' ... 
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=debian  version=any-version  codename=bullseye  arch=aarch64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ... 
   OK: Checking for apt dependency 'ca-certificates' ... 
   OK: Checking for apt dependency 'gnupg' ... 
   OK: Checking for apt signed-by key support ...                 
   OK: Importing 'thinedge/tedge-release' repository GPG keys ...
   OK: Checking if upstream install config is OK ... 
   OK: Installing 'thinedge/tedge-release' repository via apt ... 
   OK: Updating apt repository metadata cache ... 
   OK: The repository has been installed successfully - You're ready to rock!


Downloading https://dl.cloudsmith.io/public/thinedge/community/setup.deb.sh...OK
Using repository arch: aarch64
Executing the  setup script for the 'thinedge/community' repository ...

   OK: Checking for required executable 'curl' ... 
   OK: Checking for required executable 'apt-get' ... 
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=debian  version=any-version  codename=bullseye  arch=aarch64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ... 
   OK: Checking for apt dependency 'ca-certificates' ... 
   OK: Checking for apt dependency 'gnupg' ... 
   OK: Checking for apt signed-by key support ...             
   OK: Importing 'thinedge/community' repository GPG keys ...
   OK: Checking if upstream install config is OK ... 
   OK: Installing 'thinedge/community' repository via apt ... 
   OK: Updating apt repository metadata cache ... 
   OK: The repository has been installed successfully - You're ready to rock!

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tedge-full : Depends: tedge (= 1.0.2~62+gb2f0d0d) but 1.0.2~69+gef7c455 is to be installed
              Depends: tedge-mapper (= 1.0.2~62+gb2f0d0d) but 1.0.2~69+gef7c455 is to be installed
              Depends: tedge-agent (= 1.0.2~62+gb2f0d0d) but 1.0.2~69+gef7c455 is to be installed
              Depends: tedge-watchdog (= 1.0.2~62+gb2f0d0d) but 1.0.2~69+gef7c455 is to be installed
              Depends: tedge-apt-plugin (= 1.0.2~62+gb2f0d0d) but 1.0.2~69+gef7c455 is to be installed
              Depends: c8y-remote-access-plugin (= 1.0.2~62+gb2f0d0d) but 1.0.2~69+gef7c455 is to be installed
              Depends: c8y-firmware-plugin (= 1.0.2~62+gb2f0d0d) but 1.0.2~69+gef7c455 is to be installed
E: Unable to correct problems, you have held broken packages.

--------------- machine details ---------------------
date:           Wed Mar 13 08:53:39 CET 2024
tedge:          
Machine:        Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
Architecture:   arm64
Package Arch:   aarch64
Distribution:   Debian GNU/Linux 11 (bullseye)

--------------- error details ------------------------
Package management dependencies met
Detected package manager: apt
Using repository arch: aarch64
Using repository arch: aarch64
------------------------------------------------------
```
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision] Raspberry PI 3 
 - System-Architecture : `Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by reubenmiller** [comment] 2024-03-13 08:32
Root cause looks to be that the [tedge-main](https://cloudsmith.io/~thinedge/repos/tedge-main/packages/) cloud smith repository is not receiving the virtual packages from the last few builds off main.

Here is the tedge-full debian package in cloudsmith:

<img width="1218" alt="image" src="https://github.com/thin-edge/thin-edge.io/assets/3029781/d58d46e0-2e34-42ab-a47f-76e0365fd3de">

And here is the tedge package (notice that the tedge package is newer than the tedge-full package):

<img width="824" alt="image" src="https://github.com/thin-edge/thin-edge.io/assets/3029781/c5250e34-8428-44d1-899e-358744446eeb">

**Comment by reubenmiller** [comment] 2024-03-13 08:36
Here is the offending commit (by me):

https://github.com/thin-edge/thin-edge.io/commit/bcb637bf5b220203ef314e493f5bde589ef650db

There was a small change to the build script to support also building for MacOS but for some reason this caused the building of the virtual packages to fail (and the failure is also silent, which we definitely should change!).

**Comment by reubenmiller** [comment] 2024-03-13 08:57
Root cause has been found and a PR to fix it has been created. https://github.com/thin-edge/thin-edge.io/pull/2777

**Comment by reubenmiller** [comment] 2024-03-13 09:59
For sake of completeness, the above instructions are a bit misleading about the "reproducing" the issue, as the device appears to have previously used the now problematic `main` channel. The above is using the default `release` channel, however since the `main` channel apt configuration still exists, it is used by apt.

The problem can be easily reproduced using the following command (though it will only work to reproduce the issue until the new fixed version is published, in about 30 mins time):

```sh
curl -fsSL https://thin-edge.io/install.sh | sh -s -- --channel main
```

**Comment by reubenmiller** [comment] 2024-03-13 10:18
The fix has been merged, and now the installation from the `main` channel works again.

You can verify the installation from the `main` channel by using the following command:

```
curl -fsSL https://thin-edge.io/install.sh | sh -s -- --channel main
```

**Comment by reubenmiller** [comment] 2024-03-13 10:42
We've also pulled the following versions from cloudsmith.io which where missing the tedge-full and/or tedge-minimal from the [tedge-main](https://cloudsmith.io/~thinedge/repos/tedge-main/packages/) and [tedge-main-armv6](https://cloudsmith.io/~thinedge/repos/tedge-main-armv6/packages/) repositories to prevent anyone from trying to install the problematic versions (note: only the git commit hashes are provided):

* 6d79a7e
* ef7c455
* 78aa757
* bcb637b

**Comment by gligorisaev** [comment] 2024-03-14 08:00
QA has thoroughly checked the bug and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and it's not reproducable anymore

**Closed** 2024-03-14 09:54 UTC
Labels: bug
