### ISSUE TITLE
Leftover lock files in /var/run/lock

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#886] opened 2022-02-16 11:36 UTC
**Describe the bug**

It appears that we have some left-over .lock files. We should think of removing them

![image](https://user-images.githubusercontent.com/75477722/154256238-da23a6c1-2f65-43bb-a1ef-76821006a199.png)

**To Reproduce**

    sudo dpkg -P tedge_mapper tedge_apt_plugin tedge_agent tedge
    ls -lah /var/run/lock/tedge*

**Expected behavior**
Lock files are removed either while stopping the service or when the package is removed.

**Update: Workaround**
`sudo rm -f /run/lock/tedge* /run/lock/sm-c8y-mapper.lock`

**Comment by abelikt** [comment] 2022-02-16 12:06
This also seems to cause an installation issue:
![image](https://user-images.githubusercontent.com/75477722/154261323-bbc2a9a4-985b-4fa7-9389-cb2706f396e9.png)

**Workaround:** 
    sudo rm -f /run/lock/tedge* /run/lock/sm-c8y-mapper.lock

**Comment by abelikt** [comment] 2022-02-16 12:08
A little something would be also to rename sm-c8y-mapper.lock to tedge-sm-c8y-mapper.lock

**Comment by rina23q** [comment] 2022-02-16 14:39
I also encountered the same issue to upgrade my packages from 0.5.2 to 0.5.3 by `get-thin-edge_io.sh` script.

A quick workaround is definitely to remove all lock files manually. However, it is not convenient for users.

The difference recently we made is to start mapper and agent process after installation. Do we really need it? 

```
rina@SAG-CFPPNV2-U:~/thinedge/thin-edge-fork$ curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s
Thank you for trying thin-edge.io! 

Version argument has not been provided, installing latest: 0.5.3
....
Setting up tedge_agent (0.5.2) ...
2022-02-16T14:31:19.580+00:00 ERROR flockfile::unix: Another instance of tedge_agent is running.
2022-02-16T14:31:19.580+00:00 ERROR flockfile::unix: Lock file path: /run/lock/tedge_agent.lock
Error: Couldn't acquire file lock.

Caused by:
    Permission denied (os error 13)
...
```

After removing `tedge_agent.lock`, then re-ran the script. Then the same error for mapper.

```
Setting up tedge_mapper (0.5.3) ...
2022-02-16T14:34:20.602+00:00 ERROR flockfile::unix: Another instance of sm-c8y-mapper is running.
2022-02-16T14:34:20.602+00:00 ERROR flockfile::unix: Lock file path: /run/lock/sm-c8y-mapper.lock
Error: Couldn't acquire file lock.

Caused by:
    Permission denied (os error 13)
dpkg: error processing package tedge_mapper (--install):
```

**Comment by rina23q** [comment] 2022-02-16 15:09
Now I have the root cause in my mind.

In `postinst` script, now we run `tedge_agent --init`, this process is run by `root` user. This means, it tries to create a lock file **owned by root**. 
If user has already installed tedge_mapper and tedge_agent in their devices, and run `tedge connect`, the device already have lock files under `/run/lock` owned by `tedge-mapper` or `tedge-agent`. That's why postinst script fails to acquire locks.

Possible solutions:
1) Change the code of `tedge_agent --init` to remove the existing lock file if it exists. Afterwards, run --init. Then, remove the lock file owned by root.
2) `postrm` script removes all lock files.

**Comment by didier-wenzek** [comment] 2022-02-16 15:35
Remove the lock with `tedge_agent --init` will create other issues.

* On `postrm` script this is okay to remove the lock files.
* On install I would run `sudo -u tedge-agent tedge_agent --init`.

**Comment by didier-wenzek** [comment] 2022-02-16 15:48
The issue is not that the lock files are still present but that they are owned by root preventing the tedge mapper and agent users to set a lock on these files.

**Comment by rina23q** [comment] 2022-02-16 16:54
@abelikt which OS do you use?

I encountered this issue on Ubuntu 20.04, however, no issue on Raspberry Pi OS.

**Comment by rina23q** [comment] 2022-02-16 17:13
I run this as a normal user, then run as root user, then I got `./hello.sh: line 5: /run/lock/hello.lock: Permission denied` on Ubuntu. However, no permission error on RPi.

```
#!/bin/bash

LOCKFILE=/run/lock/hello.lock

exec {fd}> "${LOCKFILE}"
{
  flock -x ${fd}
  {
    while true
    do
      echo "hello world"
      sleep 30
    done
  }
  flock -u ${fd}
}
echo "end"
```

**Comment by PradeepKiruvale** [comment] 2022-02-18 05:23
> A little something would be also to rename sm-c8y-mapper.lock to tedge-sm-c8y-mapper.lock

This will go away once the mappers are merged. There will be only one tedge-mapper-c8y

**Closed** 2022-02-21 13:29 UTC
Labels: bug, WIP
