### ISSUE TITLE
Update tedge-watchdog to use the `te` MQTT topics.

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2308] opened 2023-09-29 18:21 UTC
`tedge-watchdog` has to be updated to:

- Use the [new topic scheme](https://thin-edge.github.io/thin-edge.io/next/references/mqtt-api/#health-check)
- Send health-check requests on the `cmd/health/check` channels of the watched services.
- Expect health status on the `status/health` of the the watched services.
- Be extended to run on a child device to watch the daemons running on this device.
  Note, that it makes no sense for `tedge-watchdog` to watch daemons running on a *different* device as the point is to restart them if not responding.

In practice:

- `tedge-watchdog` has to read the tedge config to get the `mqtt.topic_root` and its `mqtt.device_topic_id`. Only the services running on `mqtt.device_topic_id` have to be watched.
- As a first step `tedge-watchdog` can assume that the topic identifiers of the watched services are built using the default MQTT scheme ( `device/main//` -> `device/main/service/tedge-agent`). However, the goal is for `tedge-watchdog` to use an `EntityStore` to get the names of the services running on its device.
- This refactoring must be synchronized with the refactoring of the thin-edge daemons: as long as a service (say `tedge-agent`) is expecting health check on the former topic (i.e. ` tedge/health-check/tedge-agent`), `tedge-watchdog` has to use this topic.

**Comment by Bravo555** [comment] 2023-10-27 10:15
Closed by #2358

**Closed by Bravo555** 2023-10-27 10:15 UTC
Labels: refactoring

**Comment by gligorisaev** [comment] 2023-11-07 06:00
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot
- tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot
- tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
- tests/RobotFramework/tests/cumulocity/software_management/software.robot
- tests/RobotFramework/tests/cumulocity/supported_operations/mapper-publishing-agent-supported-ops.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- tests/RobotFramework/tests/cumulocity/jwt/jwt_request.robot
- tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot
- tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-aws.robot
- tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-az.robot
- tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot
- [x] QA has tested the bug and could not reproduce it anymore.
