### ISSUE TITLE
Support running tedge-agent on a child device

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2018] opened 2023-06-09 07:13 UTC
**Is your feature request related to a problem? Please describe.**

The `tedge-agent` provides a nice software management plugin interface. It would be useful if the `tedge-agent` could be modified to allow it to run both on the main device and on/as a child device. This would enable users to get out-of-the-box functionality for child devices with zero coding! In the future it could also be extended to the other plugins to support reusing all of the existing components as either a main device or a child device.

**Describe the solution you'd like**

There are two areas that will need addressing to enable this feature.

**Area 1: Changes to the tedge-agent to support different runtime roles**

* Not all features of the `tedge-agent` make sense running when running as a child device, for example the http server should not be started when running as a child device.
    * Expected functionality when running as a child
        * Software management
        * Restart operation
    * Disable functionality when running as a child
        * http service
* The MQTT client id should be configurable so that the client id does not conflict with the `tedge-agent` running on the main device
* The MQTT topics used by the `tedge-agent` should be configurable to use the appropriate topics depending on its current role (e.g. running as a main device or as a child device)

**Area 2: Changes to the tedge-mapper to support sending commands to child devices**
* Change the `tedge-mapper` to support routing the operations for child devices to `tedge/` topics. For example `tedge/child/{childid}/commands/...`. The specifics of the topic naming is dependent on #2005

**Notes**

* The [tedge-mapper-template](https://github.com/reubenmiller/tedge-mapper-template) PoC could be used to try out possible new MQTT topic structures before the changes are done to the `tedge-mapper`

**Describe alternatives you've considered**

**Additional context**

An [PoC](https://github.com/thin-edge/thin-edge.io/compare/main...reubenmiller:thin-edge.io:exp-topic-prefix) has already been created to show how the MQTT client id and the topics could be made configurable. A configurable topic prefix is used to control whether the `tedge-agent` should behave as a main device or a child device.

**Comment by reubenmiller** [comment] 2023-10-30 16:17
@didier-wenzek Can you please update the status of this ticket?

**Comment by didier-wenzek** [comment] 2023-10-30 17:23
Child-support has been implemented by https://github.com/thin-edge/thin-edge.io/pull/2307.
The agent documentation has been updated: https://github.com/thin-edge/thin-edge.io/pull/2235:
- [x] How to launch tedge-agent on the main device as well as on a child device
- [x] Tedge MQTT v1 protocol used by the agent for `restart` of device (main or child)
- [x] Tedge MQTT v1  protocol used by the agent for `software_list` of device (main or child)
- [x] Tedge MQTT v1  protocol used by the agent for `software_update` of device (main or child)

Topic used for health checks have been updated by https://github.com/thin-edge/thin-edge.io/issues/2274.
Documentation is addressed by https://github.com/thin-edge/thin-edge.io/pull/2375
- [x] Publish health status on `te/$(agent-service-id)/status/health` for agent running on main or child device.
- [x] Respond to health check on  `te/$(agent-service-id)/cmd/health/check` for agent running on main or child device.
- [x] Respond to health check on  `te/$(device-id)/cmd/health/check` for agent running on main or child device.

**Comment by gligorisaev** [comment] 2023-11-02 07:17
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
- tests/RobotFramework/tests/cumulocity/restart/restart_device.robot
- tests/RobotFramework/tests/cumulocity/restart/restart_device_child.robot
- tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
- [x] QA has tested the bug and could not reproduce it anymore.

**Closed** 2023-11-02 07:23 UTC
Labels: idea, theme:software, theme:mqtt
