### ISSUE TITLE
Tests should cope with retained messages

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1081] opened 2022-04-13 10:11 UTC
**Describe the bug**

Our current system tests should cope with retained messages.

At least those are affected:
- caused by retained messages
- same locally : caused by retained messages

We should make them resilient against retained messages when subcribing or check if it is possible to convert them to Rust.

A retained message was added here:

https://github.com/thin-edge/thin-edge.io/issues/862

**To Reproduce**

`pysys.py run <test_name>
`
**Expected behavior**
works

**Comment by didier-wenzek** [comment] 2022-04-13 15:00
This issue is a bit cryptic! I have to guess. Do you mean that some tests are broken because subscribing to `#` and so receiving previously published retained messages?

**Comment by abelikt** [comment] 2022-04-14 08:12
Exactly, that's the case. Some are subscribing and run an assertion on the output. When these retained messages should be there, we need to update or remove the tests.

**Comment by rina23q** [comment] 2022-04-19 10:20
@abelikt will add the tests to be fixed.

Solution:
* Tests should subscribe only the topic(s) that the test is interested in. Don't use '#'.

**Comment by rina23q** [comment] 2022-07-28 09:01
As we discussed in the past, the issue is that we didn't subscribe the precise topic. The problem is in our pysys tests themselves. All system tests are planned to move to our new framework. Therefore, I would close the issue.

**Closed by rina23q** 2022-07-28 09:01 UTC
Labels: bug, willwork
