### ISSUE TITLE
Flaky test mapper_fails_during_sw_update_recovers_and_process_response test

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1879] opened 2023-03-31 12:03 UTC
**Describe the bug**

The test `tedge_mapper::c8y::tests::mapper_fails_during_sw_update_recovers_and_process_response` is failing quite frequently on `cargo test` runs.

**To Reproduce**

Run `cargo test -p tedge-mapper c8y::tests::mapper_fails_during_sw_update_recovers_and_process_response` repeatedly. It fails at least once in every three attempts.

**Additional Context**

It was reported in the past in [#570](https://github.com/thin-edge/thin-edge.io/issues/570) and fixed with https://github.com/thin-edge/thin-edge.io/pull/575

**Comment by didier-wenzek** [comment] 2023-03-31 14:27
Another test is flaky:

```
 ---- tests::test_fs_events stdout ----
thread 'tests::test_fs_events' panicked at 'assertion failed: `(left == right)`
  left: `Some(Modified("/tmp/.tmpuU7RpW/dir_b/file_b"))`,
 right: `Some(Modified("/tmp/.tmpuU7RpW/file_a"))`', /home/runner/work/thin-edge.io/thin-edge.io/crates/core/tedge_actors/src/test_helpers.rs:274:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by didier-wenzek** [comment] 2023-03-31 19:24
Yet another one - from the system test suite

<h3 dir="auto">Failed Tests</h3>


Name | Message | Duration | Suite
-- | -- | -- | --
Software list should be populated during startup | Managed object does not have a c8y_SoftwareList fragment | 165.316 s | Software

**Comment by didier-wenzek** [comment] 2023-03-31 19:25
This PR temporary ignores the flaky integration tests: https://github.com/thin-edge/thin-edge.io/pull/1882.

**Comment by gligorisaev** [comment] 2023-06-13 05:40
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.

**Comment by didier-wenzek** [comment] 2024-01-16 09:03
Closing as these tests have been definitely removed.

**Closed by didier-wenzek** 2024-01-16 09:03 UTC
Labels: bug, theme:testing
