### ISSUE TITLE
Draft "Robust Self-Update of thin-edge.io" feature

### ISSUE THREAD

**Issue by mbie-sag** [thin-edge/thin-edge.io#555] opened 2021-11-03 09:41 UTC
When using thin-edge.io in a remote location connected to Cumulocity IoT, I would like to use Cumulocity´s Device Management to trigger an update of thin-edge.io itself to a newer version.
The update process needs to be highly robust and handling automatic rollback in the case of any issues during the installation to prevent manual interaction or disconnected device situations.

tedge-updater is a seperate component

AC:

- POC for self-update
- Rollback

**Comment by itsyitsy** [comment] 2021-12-07 15:37
Work on this ticket will from now on be on Milestone [thin-edge self-updating](https://github.com/thin-edge/thin-edge.io/milestone/6)

**Comment by didier-wenzek** [comment] 2022-07-18 15:27
Duplicate of https://github.com/thin-edge/thin-edge.io/issues/760

**Closed** 2022-07-18 15:28 UTC
Labels: duplicate, idea
